apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilender-loan
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: loan
spec:
  selector:
    matchLabels:
      app: ilender-application
      subname: loan
  replicas: 1
  template:
    metadata:
      labels:
        app: ilender-application
        subname: loan
    spec:
      containers:
        - name: ilender-loan
          image: "gandigit/ilender-loan-demo:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9074
              protocol: TCP
            - name: https
              containerPort: 8082
          # resources:
          #   requests:
          #     memory: "500Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /loan
          #     port: my-http
          #   initialDelaySeconds: 120
          # failureThreshold: 60
          # readinessProbe:
          #   httpGet:
          #     path: /loan
          #     port: my-http
          #   initialDelaySeconds: 120
          env:
            - name: MY_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_CONTAINER_NAME
              value: ilender-loan
            - name: MY_CONTAINER_IMAGE
              value: "gandigit/ilender-loan-demo:0.0.1"
            - name: MY_LABELS_APP
              # value: loanservice
              value: ilender-loan
            - name: MY_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: skipExternalLog
              value: "FALSE"
          envFrom:
            - configMapRef:
                name: ilender-configmap-urls
            - configMapRef:
                name: ilender-configmap-db
            - configMapRef:
                name: ilender-configmap-mq
            - configMapRef:
                name: ilender-configmap-eventstream
            - configMapRef:
                name: ilender-configmap-common

---
apiVersion: v1
kind: Service
metadata:
  name: ilender-loan
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: loan
spec:
  type: ClusterIP
  ports:
    - name: my-http
      port: 9090
      targetPort: my-http
  selector:
    app: ilender-application
    subname: loan
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ilender-loan
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: loan
spec:
  path: /loan
  to:
    kind: Service
    name: ilender-loan
    weight: 100
  port:
    targetPort: my-http
