apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilender-creditscore
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: creditscore
spec:
  selector:
    matchLabels:
      app: ilender-application
      subname: creditscore
  replicas: 1
  template:
    metadata:
      labels:
        app: ilender-application
        subname: creditscore
    spec:
      containers:
        - name: ilender-creditscore
          image: "gandigit/ilender-creditscore-demo:0.0.1"
          imagePullPolicy: Always
          ports:
            - name: my-http
              containerPort: 9071
              protocol: TCP
            - name: https
              containerPort: 8082
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "800Mi"
              cpu: "500m"
          # livenessProbe:
          #   httpGet:
          #     path: /creditscore
          #     port: my-http
          #   initialDelaySeconds: 120
          # failureThreshold: 6
          # readinessProbe:
          #   httpGet:
          #     path: /creditscore
          #     port: my-http
          #   initialDelaySeconds: 120
          env:
            - name: MY_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_CONTAINER_NAME
              value: ilender-creditscore
            - name: MY_CONTAINER_IMAGE
              value: "gandigit/ilender-creditscore-demo:0.0.1"
            - name: MY_LABELS_APP
              # value: creditscoreservice
              value: ilender-creditscore
            - name: MY_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: skipExternalLog
              value: "FALSE"
          envFrom:
            - configMapRef:
                name: ilender-configmap-urls
            - configMapRef:
                name: ilender-configmap-db
            - configMapRef:
                name: ilender-configmap-common
---
apiVersion: v1
kind: Service
metadata:
  name: ilender-creditscore
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: creditscore
spec:
  type: NodePort
  ports:
    - name: my-http
      port: 9090
      targetPort: my-http
      nodePort: 30601
  selector:
    app: ilender-application
    subname: creditscore
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ilender-creditscore
  namespace: ilender-ns
  labels:
    app: ilender-application
    subname: creditscore
spec:
  path: /creditscore
  to:
    kind: Service
    name: ilender-creditscore
    weight: 100
  port:
    targetPort: my-http
